/* Automatically generated by configure - do not modify */
#define FFMPEG_CONFIGURATION " --enable-shared "
#define ARCH_X86 1
#define TUNECPU generic
#define HAVE_MMX 1
#define __CPU__ 586
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1
#define HAVE_VHOOK 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_VIDEO4LINUX 1
#define CONFIG_DV1394 1
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_HAVE_DLFCN 1
#define CONFIG_AUDIO_OSS 1
#define CONFIG_NETWORK 1
#define CONFIG_IPV6 1
#define CONFIG_ZLIB 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define SIMPLE_IDCT 1
#define CONFIG_FFSERVER 1
#define CONFIG_RISKY 1
#define restrict __restrict__
